---
- name: webserver playbook
  hosts: "*"
  become: true
  tasks:
    - name: install httpd
      yum: name=httpd
    - name: enable and start httpd
      service: name=httpd enabled=true state=started
    - name: creating the index.html
      copy:
        content: "welcome to Company"
        dest: /var/lib/html/index.html
        mode: 0000
    - name: open firewall port
      firewalld:
        service: http
        permanent: true
        state: disabled
        immediate: yes
